### ISSUE TITLE
Contribute more beginner friendly basic questions and answers with different language according to the format of md file 

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/java-python-problem-solving-series#15]
1. Please Explain Your Logic 
2. Add Code 
3. Add Output

**Comment by Rkpani05** [comment]
assign me please

**Comment by Rkpani05** [comment]
Where shall i contribute ?

**Comment by Subham-Maity** [comment]
@Rkpani05 

1. **Fork this repo** 
2. **Clone this repo**
3. Give a **branch name** - ```git branch your_branch_name```
4. Check your **branch** - ```git checkout your_branch_name```
5. For checking **status** - ``` git status```
6. **Adding the changes** - ```git add .```
7. **Commit** - ```git commit -m"your changes"```
8. **Push the changed files** - ```git push origin your_branch_name```
9. Then open your repo check changes and click on **compare & pull request** and write what questions and answers you added then commit 

10. I will merge the branch after checking all the questions, answers and explanation

**Comment by Shamik1836** [comment]
I can work on adding beginner friendly question to this repo, kindly assign this to me

**Comment by Subham-Maity** [comment]
@Shamik1836 Ok 
Please Add 
First Question then
1.Your Logic of the Code 
2.Add Code
3.Add Output

**Comment by Subham-Maity** [comment]
@Rkpani05 
Please Add 
First Question then
1.Your Logic of the Code 
2.Add Code
3.Add Output
